name: Build and Deploy Slidev Presentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Clear npm cache and install dependencies
      - name: Clear npm cache and install dependencies
        run: |
          rm -rf node_modules
          npm cache clean --force
          cd presentation  # Change to the presentation directory
          npm install

      # Build the Slidev presentation from the presentation directory
      - name: Build the Slidev presentation
        run: |
          cd presentation
          npm run build -- --base '/intro-to-ml-GVP/'  # Set the correct base URL for GitHub Pages

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Target branch for GitHub Pages
          folder: ./presentation/dist  # Folder containing the built files
          clean: true  # Clean the target branch before deployment
